version: 2.1

executors:
  android-executor:
    docker:
      - image: ubuntu:20.04
    working_directory: ~/project

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install Required Tools
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            apt-get install -y wget unzip openjdk-17-jdk

      - run:
          name: Install Android SDK Command Line Tools
          command: |
            wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
            mkdir -p $ANDROID_HOME/cmdline-tools
            unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
            rm cmdline-tools.zip
            yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses
            $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"

      - run:
          name: Set Up Local Properties
          command: |
            echo "sdk.dir=$ANDROID_HOME" > local.properties

      - run:
          name: Grant Execute Permission to Gradle Wrapper
          command: chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

      - run:
          name: Run Build
          command: ./gradlew build

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results
          
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
