version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/openjdk:17-jdk
    working_directory: ~/project

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install Android SDK
          command: |
            sudo apt-get update -y
            sudo apt-get install -y wget unzip
            wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
            unzip cmdline-tools.zip
            sudo mkdir -p /usr/local/android-sdk/cmdline-tools
            sudo mv cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
            export ANDROID_SDK_ROOT=/usr/local/android-sdk
            export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
            yes | sdkmanager --licenses
            sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"
      - run:
          name: Set Java 17 Environment Variables
          command: |
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
            echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $BASH_ENV
            source $BASH_ENV
            java -version
      - run:
          name: Setup Gradle Wrapper
          command: ./gradlew wrapper --gradle-version 8.9
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: apk
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
