version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/project

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-17-jdk -y
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
            sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1
            java -version
      - run:
          name: Download and setup dependencies
          command: sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache-
      - run:
          name: Setup Gradle Wrapper
          command: ./gradlew wrapper --gradle-version 8.9
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: apk
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
