version: 2.1

executors:
  android-executor:
    docker:
      - image: ubuntu:20.04
    working_directory: ~/project

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install Required Tools
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            apt-get install -y wget unzip openjdk-17-jdk

      - run:
          name: Grant Execute Permission to Gradle Wrapper
          command: chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: apk

      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
